"""Public data contracts for staged RepoAudit integrations."""

from .errors import (
    ErrorId,
    StructuredError,
    new_error_id,
    validate_error_id,
)
from .event_writer import (
    DEFAULT_MAX_EVENT_BYTES,
    MIN_MAX_EVENT_BYTES,
    EventWriteError,
    EventWriter,
)
from .events import (
    EVENTS_REQUIRING_CANDIDATE,
    EVENTS_REQUIRING_PATH,
    EVENT_REQUIRED_PAYLOAD_KEYS,
    EVENT_TYPES,
    RUN_COMPLETION_STATUSES,
    AnalysisEvent,
    EventId,
    new_event_id,
    validate_event_id,
)
from .models import (
    SCHEMA_VERSION,
    AuditCandidate,
    AuditRun,
    CandidateId,
    DataFlowPath,
    DataFlowStep,
    PathId,
    RepositoryProfile,
    RunId,
    SourceLocation,
    SourceSinkPair,
    ValidationResult,
    make_candidate_id,
    make_path_id,
    new_run_id,
    utc_now,
    validate_candidate_id,
    validate_path_id,
    validate_run_id,
)

__all__ = [
    "SCHEMA_VERSION",
    "AuditCandidate",
    "AuditRun",
    "CandidateId",
    "DataFlowPath",
    "DataFlowStep",
    "DEFAULT_MAX_EVENT_BYTES",
    "EVENT_TYPES",
    "EVENTS_REQUIRING_CANDIDATE",
    "EVENTS_REQUIRING_PATH",
    "EVENT_REQUIRED_PAYLOAD_KEYS",
    "RUN_COMPLETION_STATUSES",
    "ErrorId",
    "EventId",
    "EventWriteError",
    "EventWriter",
    "AnalysisEvent",
    "MIN_MAX_EVENT_BYTES",
    "PathId",
    "RepositoryProfile",
    "RunId",
    "SourceLocation",
    "SourceSinkPair",
    "StructuredError",
    "ValidationResult",
    "make_candidate_id",
    "make_path_id",
    "new_error_id",
    "new_event_id",
    "new_run_id",
    "utc_now",
    "validate_candidate_id",
    "validate_error_id",
    "validate_event_id",
    "validate_path_id",
    "validate_run_id",
]
